---
collections:
  - name: amazon.aws
  - name: ansible.platform
  - name: ansible.controller
  - name: redhat.satellite
  - name: redhat.satellite_operations
  - name: redhat.rhel_system_roles
  - name: ansible.posix
  - name: community.general